version: '3.9'

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                VERSION: ${PHP_VERSION:-8.1}
        expose:
            - 9000
        ports:
            - "5173:5173"
        restart: unless-stopped
        environment:
            ROLE: app
            APPENV: ${APP_ENV:-production}
        volumes:
            - ./docker/php.ini:/etc/php/${PHP_VERSION}/cli/conf.d/php.ini
            - .:/var/www/html
        networks:
            - ccisnet
        depends_on:
            - mysql

    webserver:
        image: nginx:1.23.3-alpine
        ports:
            - "8007:80"
        restart: unless-stopped
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
        volumes:
            - ./docker/default.conf.template:/etc/nginx/templates/default.conf.template
            - ./:/var/www/html
        networks:
            - ccisnet
        depends_on:
            - app
            - mysql

    mysql:
        image: mariadb:10.9.3-jammy
        ports:
            - "3307:3306"
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: "${DB_DATABASE:-secret}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
            MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
            MYSQL_USER: "${DB_USERNAME:-secret}"
            # SERVICE_TAGS: dev
            # SERVICE_NAME: mysql
        volumes:
            - data:/var/lib/mysql
        networks:
            - ccisnet
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u${DB_USERNAME}",
                    "-p${DB_PASSWORD}"
                ]
            retries: 3
            timeout: 5s

networks:
    ccisnet:
        driver: bridge

volumes:
    data:
        driver: local
